"""create sips table

Revision ID: 2268707a3444
Revises: 9e053015efa8
Create Date: 2026-07-06 13:45:19.090972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2268707a3444'
down_revision: Union[str, Sequence[str], None] = '9e053015efa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scheme_code', sa.Integer(), nullable=False),
    sa.Column('scheme_name', sa.String(length=255), nullable=False),
    sa.Column('monthly_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sip_date', sa.Integer(), nullable=False),
    sa.Column('next_investment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sips')
    # ### end Alembic commands ###
