"""create portfolio table

Revision ID: a24edfc86389
Revises: a873d7cf8fcf
Create Date: 2026-07-06 09:52:01.925719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a24edfc86389'
down_revision: Union[str, Sequence[str], None] = 'a873d7cf8fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scheme_code', sa.Integer(), nullable=False),
    sa.Column('scheme_name', sa.String(length=255), nullable=False),
    sa.Column('investment_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('purchase_nav', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('units', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio')
    # ### end Alembic commands ###
